"""Brief assembly — builds the final cited brief dict (conforms to BriefSchema in
@cadenza/shared). Compact mirror of the prototype's brief content; real synthesis
replaces this when live LLM calls land.
"""

from __future__ import annotations

from typing import Any

_BRIEFS: dict[str, dict[str, Any]] = {
    "Market for AI scheduling assistants for US dental clinics": {
        "title": "AI Scheduling Assistants for US Dental Clinics — Market Brief",
        "market": "The US has ~183,000 practicing dentists across ~135,000 practices [Source 1]; front-desk no-shows cost a typical practice $50,000–$70,000/yr [Source 2]. Adoption is concentrated in multi-location DSOs first.",
        "competitors": "Three patient-communication platforms [Source 3] bundle AI scheduling at $300–$800 per location per month. None offers a fully autonomous, code-owned agent.",
        "gap": "A custom, owned scheduling agent integrated with a clinic's practice-management software. Mid-size DSOs (5–40 locations) are underserved and have budget.",
        "sources": [
            "ADA Health Policy Institute — Supply of Dentists in the US (2024)",
            "Dental practice operations & no-show cost analysis (2025)",
            "Patient-communication platform pricing pages (accessed Jun 2026)",
        ],
    },
}

_DEFAULT = "Market for AI scheduling assistants for US dental clinics"


def build_brief(query: str, model_label: str, mode: str, run_id: str) -> dict[str, Any]:
    seed = _BRIEFS.get(query, _BRIEFS[_DEFAULT])
    sources = seed["sources"]
    suffix = "(your key)" if mode == "live" else "(cached demo)"
    return {
        "title": seed["title"],
        "byline": f"Generated by Cadenza on {model_label} {suffix} · {len(sources)} sources · claim-verified",
        "query": query,
        "model": model_label,
        "mode": mode,
        "sections": [
            {"heading": "Market opportunity", "body": seed["market"]},
            {"heading": "Competitive landscape", "body": seed["competitors"]},
            {"heading": "Where Devs Core could win", "body": seed["gap"]},
        ],
        "sources": [{"id": f"Source {i + 1}", "label": s} for i, s in enumerate(sources)],
        "claimsVerified": {"verified": 3, "total": 3},
        "permalink": f"cadenza.devs-core.com/run/{run_id}",
    }
